application: ass3-octo-freezing-ironman
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /app/.*
  script: main.app
  secure: always
  
- url: /
  static_dir: interface

